# Generated by Django 3.2.8 on 2021-10-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.CharField(max_length=100)),
                ('EndDate', models.CharField(max_length=100)),
                ('Leaveday', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'applyleave',
            },
        ),
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='password1',
        ),
        migrations.AlterModelTable(
            name='mymodel',
            table='employee',
        ),
    ]
